// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO match (
    public_id,
    white_user_id,
    black_user_id,
    white_display_name,
    black_display_name,
    initial_time_ms,
    increment_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, public_id, white_user_id, black_user_id, white_display_name, black_display_name, initial_time_ms, increment_ms, created_at
`

type CreateMatchParams struct {
	PublicID         string
	WhiteUserID      pgtype.Int8
	BlackUserID      pgtype.Int8
	WhiteDisplayName string
	BlackDisplayName string
	InitialTimeMs    int64
	IncrementMs      int64
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.PublicID,
		arg.WhiteUserID,
		arg.BlackUserID,
		arg.WhiteDisplayName,
		arg.BlackDisplayName,
		arg.InitialTimeMs,
		arg.IncrementMs,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WhiteUserID,
		&i.BlackUserID,
		&i.WhiteDisplayName,
		&i.BlackDisplayName,
		&i.InitialTimeMs,
		&i.IncrementMs,
		&i.CreatedAt,
	)
	return i, err
}

const insertMatchEvent = `-- name: InsertMatchEvent :one
INSERT INTO match_event (
    match_id,
    seq_num,
    event_type,
    payload
) VALUES (
    $1, $2, $3, $4
) RETURNING id, match_id, seq_num, event_type, payload, created_at
`

type InsertMatchEventParams struct {
	MatchID   int64
	SeqNum    int32
	EventType MatchEventType
	Payload   []byte
}

func (q *Queries) InsertMatchEvent(ctx context.Context, arg InsertMatchEventParams) (MatchEvent, error) {
	row := q.db.QueryRow(ctx, insertMatchEvent,
		arg.MatchID,
		arg.SeqNum,
		arg.EventType,
		arg.Payload,
	)
	var i MatchEvent
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.SeqNum,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
