// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO match (
    public_id,
    white_user_id,
    black_user_id,
    white_display_name,
    black_display_name,
    initial_time_ms,
    increment_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, public_id, white_user_id, black_user_id, white_display_name, black_display_name, initial_time_ms, increment_ms, created_at
`

type CreateMatchParams struct {
	PublicID         string
	WhiteUserID      pgtype.Int8
	BlackUserID      pgtype.Int8
	WhiteDisplayName string
	BlackDisplayName string
	InitialTimeMs    int64
	IncrementMs      int64
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.PublicID,
		arg.WhiteUserID,
		arg.BlackUserID,
		arg.WhiteDisplayName,
		arg.BlackDisplayName,
		arg.InitialTimeMs,
		arg.IncrementMs,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WhiteUserID,
		&i.BlackUserID,
		&i.WhiteDisplayName,
		&i.BlackDisplayName,
		&i.InitialTimeMs,
		&i.IncrementMs,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchByPublicID = `-- name: GetMatchByPublicID :one
SELECT id, public_id, white_user_id, black_user_id, white_display_name, black_display_name, initial_time_ms, increment_ms, created_at FROM match
WHERE public_id = $1
`

func (q *Queries) GetMatchByPublicID(ctx context.Context, publicID string) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByPublicID, publicID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WhiteUserID,
		&i.BlackUserID,
		&i.WhiteDisplayName,
		&i.BlackDisplayName,
		&i.InitialTimeMs,
		&i.IncrementMs,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchEventsByMatchID = `-- name: GetMatchEventsByMatchID :many
SELECT id, match_id, seq_num, event_type, payload, created_at FROM match_event
WHERE match_id = $1
ORDER BY seq_num ASC
`

func (q *Queries) GetMatchEventsByMatchID(ctx context.Context, matchID int64) ([]MatchEvent, error) {
	rows, err := q.db.Query(ctx, getMatchEventsByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchEvent
	for rows.Next() {
		var i MatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.SeqNum,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEndedMatches = `-- name: GetUserEndedMatches :many
SELECT 
    m.public_id,
    m.white_user_id,
    m.black_user_id,
    m.white_display_name,
    m.black_display_name,
    wu.username AS white_username,
    bu.username AS black_username,
    m.initial_time_ms,
    m.increment_ms,
    m.created_at,
    e.payload AS ended_payload,
    (SELECT COUNT(*) FROM match_event me WHERE me.match_id = m.id AND me.event_type = 'move') AS move_count
FROM match m
INNER JOIN match_event e ON e.match_id = m.id AND e.event_type = 'game_ended'
LEFT JOIN users wu ON wu.id = m.white_user_id
LEFT JOIN users bu ON bu.id = m.black_user_id
WHERE m.white_user_id = $1 OR m.black_user_id = $1
ORDER BY m.created_at DESC
`

type GetUserEndedMatchesRow struct {
	PublicID         string
	WhiteUserID      pgtype.Int8
	BlackUserID      pgtype.Int8
	WhiteDisplayName string
	BlackDisplayName string
	WhiteUsername    pgtype.Text
	BlackUsername    pgtype.Text
	InitialTimeMs    int64
	IncrementMs      int64
	CreatedAt        pgtype.Timestamptz
	EndedPayload     []byte
	MoveCount        int64
}

func (q *Queries) GetUserEndedMatches(ctx context.Context, userID pgtype.Int8) ([]GetUserEndedMatchesRow, error) {
	rows, err := q.db.Query(ctx, getUserEndedMatches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserEndedMatchesRow
	for rows.Next() {
		var i GetUserEndedMatchesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.WhiteUserID,
			&i.BlackUserID,
			&i.WhiteDisplayName,
			&i.BlackDisplayName,
			&i.WhiteUsername,
			&i.BlackUsername,
			&i.InitialTimeMs,
			&i.IncrementMs,
			&i.CreatedAt,
			&i.EndedPayload,
			&i.MoveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMatchEvent = `-- name: InsertMatchEvent :one
INSERT INTO match_event (
    match_id,
    seq_num,
    event_type,
    payload
) VALUES (
    $1, $2, $3, $4
) RETURNING id, match_id, seq_num, event_type, payload, created_at
`

type InsertMatchEventParams struct {
	MatchID   int64
	SeqNum    int32
	EventType MatchEventType
	Payload   []byte
}

func (q *Queries) InsertMatchEvent(ctx context.Context, arg InsertMatchEventParams) (MatchEvent, error) {
	row := q.db.QueryRow(ctx, insertMatchEvent,
		arg.MatchID,
		arg.SeqNum,
		arg.EventType,
		arg.Payload,
	)
	var i MatchEvent
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.SeqNum,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
