// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int64
	Username       string
	DisplayName    string
	HashedPassword []byte
	CreatedAt      pgtype.Timestamptz
}
