version: '3'

tasks:
  deps:
    desc: "Download npm dependencies"
    cmds:
      - npm install
    
  test:
    desc: "Run tests"
    cmds:
      - npm test

  lint:
    desc: "Run linter"
    cmds:
      - npm run lint

  ci:
    desc: "Run full frontend ci"
    deps: [deps, test, lint]

  run:
    desc: "Run the frontend"
    cmds:
      - npm install
      - npm run dev