FROM golang:1.26-alpine AS builder
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.27.2

FROM alpine:3.23
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY ./db/migrations /migrations

ENV GOOSE_DRIVER=postgres
ENV GOOSE_DBSTRING=postgres://gochess:secret@postgres:5432/gochess?sslmode=disable

ENTRYPOINT ["goose", "-dir", "/migrations"]
CMD ["up"]

