name: Frontend

on: [push, pull_request]

jobs:
    lint:
          name: Frontend lint
          runs-on: ubuntu-latest

          steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name: Install dependencies
              run: cd frontend && npm install

            - name: Lint
              run: cd frontend && npx eslint '**/*.ts' '**/*.tsx'

    test:
        name: Frontend test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name: Install dependencies
              run: cd frontend && npm install

            - name: Test
              run: cd frontend && npm test